services:

  # Service MongoDB
  mongo_datasolutech:
    image: mongo:7 #Docker télécharge l’image officielle MongoDB
    container_name: mongodb_datasolutech #On donne un nom clair au conteneur MongoDB
    volumes:
      - volume_mongodb:/data/db   # Les données MongoDB sont sauvegardées dans un volume Docker
    ports:
      - "27018:27017" #Cela rend MongoDB accessible depuis sur le port 27017

  # Service de test
  test:
    env_file:
      - .env     
    build: 
      context: . # le . signifie le dossier courant où se trouve le docker_compose.
      dockerfile: Dockerfile.test # Docker construit l’image du script Python à partir du Dockerfile.test
    container_name: test_datasolutech
    depends_on:
      - mongo_datasolutech # Cela indique que le conteneur mongo doit être démarré avant le conteneur migration
    volumes:
      - ./donnees:/data #Le dossier local donnees est partagé avec le conteneur Python

  # Service de migration
  migration:    
    env_file:
      - .env     
    build: . # Docker construit l’image du script Python à partir du Dockerfile
    container_name: migration_datasolutech
    depends_on:
      - mongo_datasolutech # Cela indique que le conteneur mongo doit être démarré avant le conteneur migration
    volumes:
      - ./donnees:/data #Le dossier local donnees est partagé avec le conteneur Python

volumes:
  
  volume_mongodb: # volume pour les données MongoDB